### ISSUE TITLE
tg推送报错 local variable 'response' referenced before assignment

### ISSUE THREAD

**Issue by Storm4542** [wuye999/myScripts#2]
环境变量全部配好了。
log如下：
tg服务启动
推送失败！
local variable 'response' referenced before assignment

**Comment by wuye999** [comment]
删除sendNotify.py&nbsp;后再试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wuye999/myScripts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月19日(星期二) 中午11:21
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[wuye999/myScripts] tg推送报错 local variable 'response' referenced before assignment (Issue #2)





 
环境变量全部配好了。
 log如下：
 tg服务启动
 推送失败！
 local variable 'response' referenced before assignment
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Storm4542** [comment]
> 删除sendNotify.py&nbsp;后再试试
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "wuye999/myScripts" ***@***.***&gt;; 发送时间:&nbsp;2021年10月19日(星期二) 中午11:21 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[wuye999/myScripts] tg推送报错 local variable 'response' referenced before assignment (Issue #2) 环境变量全部配好了。 log如下： tg服务启动 推送失败！ local variable 'response' referenced before assignment — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

删除后，执行脚本自动下载。还是一样报错
